public class Exceptions
{

    public static void main (String args[])
    {
		
	try {
	    throw new NullPointerException();


	} catch (Exception e) {

		System.out.println("Succesful error throwing");

	}
    } // end main
    
    
} 




